### ISSUE TITLE
How to walk up the bullet robot in Gazebo or in Rviz?

### ISSUE THREAD

**Issue by TurtleZhong** [csiro-robotics/bullet_syropod#7]
Hi, I use the [syropod_highlevel_controller](https://github.com/csiro-robotics/syropod_highlevel_controller) pkg with bullet robot in simulation environment, I follow the tutorials [here](https://github.com/csiro-robotics/shc_tutorials/blob/master/shc_pc_gazebo_simulation.md) and I launch the demo use
```bash
roslaunch bullet_syropod bullet_highlevel.launch config:=bullet_insectoid gazebo:=true
```
and I use the rqt configure to control the robot, and I got this

![Screenshot from 2022-03-20 16-04-33](https://user-images.githubusercontent.com/19700579/159153995-23f39bcf-33cb-4ede-bfb5-2d4f50974b9c.png)

and in the rviz, the robot model seems wrong since the legs of bullet are not loading.
![Screenshot from 2022-03-20 16-02-17](https://user-images.githubusercontent.com/19700579/159154038-d8b44951-4ce1-4bd0-bc93-2a7ebd61e1ac.png)

So How can I walk up the bullet like this [Youtube Video](https://www.youtube.com/watch?v=bBVuBUkhu-4)

Thanks.

**Comment by TurtleZhong** [comment]
I found the solution, just click the pause button in Gazebo UI.

**Comment by wen0719** [comment]
> I found the solution, just click the pause button in Gazebo UI.
 I have this problem too.Can you tell me how to solve this.It doesn't work when click the pause button in gazebo UI

**Comment by wen0719** [comment]
ok, I solved it, using use_sim_time=true in gazebo_world.launch file
